# .github/workflows/**main.yml**

# название воркфлоу
name: Django-app workflow

# триггер для запуска 
on: [push]

# что надо сделать, если произшло событие триггер(ы) описанный в on
jobs:
  # Job №1 - покрытие тестами, поэтому назовем его tests
  tests:
    # «Раннер» — создание изолированного окружения с последней версией Ubuntu 
    runs-on: ubuntu-latest

    steps:
    # Запуск готового скрипта actions checkout для клонирования репозитория
    - uses: actions/checkout@v2
    
    # Шаг 1 : Установка питона (Set up Python)
    - name: Set up Python
      # Запуск готового скрипта  actions setup-python
      # для развёртывания окружения Python
      uses: actions/setup-python@v2
      with:
        # Выбор версии Python
        python-version: 3.7
        
    # Шаг 2 : Установка зависимостей (Install dependencies)
    - name: Install dependencies
      run: | 
        # обнрви pip
        python -m pip install --upgrade pip 
        # установи flake8 и его плагины
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        # установи зависимости
        pip install -r requirements.txt
        
    # Шаг 3 : Покрытие тестами 
    - name: Test with flake8 and django tests
      run: |
        # запуск проверки проекта по flake8
        python -m flake8
        # перейти в папку, содержащую manage.py
        # #<корневая_папка_infra_actions>/<папка_проекта>/manage.py
        cd infra_project/
        # запусти написанные разработчиком тесты
        # они лежат внутри проекта в файле tests.py
        python manage.py test

  build_and_push_to_docker_hub:
  # Job №2 - сборка образа и пуш его на докерхаб
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    # Не выполнять сразу, ждать, пока выполнится tests
    needs: tests
    
    steps:
    
      # Шаг 1 : Проверка доступности репозитория Docker Hub для workflow
      - name: Check out the repo
        uses: actions/checkout@v2 # скрипт
        
      # Шаг 2 : Вызов сборщика контейнеров docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 # скрипт
        
      # Шаг 3 : Авторизация на Docker Hub
      - name: Login to Docker 
        uses: docker/login-action@v1 # скрипт
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      # Шаг 4 : Пуш образа в Docker Hub 
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2 # скрипт
        with:
          push: true
          tags: andreibo87/infra_actions:ver.1.0 
          
